import earbudsImg from './assets/images/item_black_earbuds_1791382126065.jpg';
import idCardImg from './assets/images/item_student_id_card_1791382139577.jpg';
import backpackImg from './assets/images/item_black_backpack_1791382151987.jpg';
import calculatorImg from './assets/images/item_scientific_calculator_1791382164984.jpg';
import waterBottleImg from './assets/images/item_silver_water_bottle_1791382175998.jpg';
import { AppNotification, CampusItem, ItemMatch, OwnershipClaim, UserProfile } from './types';

export const CAMPUS_IMAGES = {
  earbuds: earbudsImg,
  idCard: idCardImg,
  backpack: backpackImg,
  calculator: calculatorImg,
  waterBottle: waterBottleImg,
};

export const INITIAL_DEMO_ITEMS: CampusItem[] = [
  {
    id: 'item_lost_earbuds_01',
    reportCode: 'FB-2026-101',
    title: 'Black Wireless Earbuds',
    description: 'Black wireless earbuds with a compact charging case.',
    additionalDetails: 'Matte black Boat Airdopes charging case with a tiny silver mark near the USB-C port.',
    category: 'Electronics',
    type: 'found',
    date: '2026-09-18',
    location: 'Central Library',
    image: earbudsImg,
    status: 'Possible Match',
    userId: 'student_tanya_01',
    reporterName: 'Tanya Garg',
    createdAt: '2026-09-18T11:20:00.000Z',
    isPublic: true,
  },
  {
    id: 'item_lost_idcard_03',
    reportCode: 'FB-2026-102',
    title: 'Blue Student ID Card',
    description: 'University student ID card inside a clear protective badge holder with blue lanyard.',
    additionalDetails: 'Has a library barcode sticker on the back.',
    category: 'ID Cards',
    type: 'lost',
    date: '2026-09-20',
    location: 'Computer Lab',
    image: idCardImg,
    status: 'Reported',
    userId: 'student_tanya_01',
    reporterName: 'Tanya Garg',
    createdAt: '2026-09-20T16:30:00.000Z',
    isPublic: true,
  },
  {
    id: 'item_found_backpack_04',
    reportCode: 'FB-2026-103',
    title: 'Black Backpack',
    description: 'Modern black canvas laptop backpack found on the wooden bench near the south coffee counter.',
    additionalDetails: 'Held safely at the Cafeteria Supervisor Desk.',
    category: 'Bags',
    type: 'found',
    date: '2026-09-22',
    location: 'Cafeteria',
    image: backpackImg,
    status: 'Reported',
    userId: 'student_kabir_03',
    reporterName: 'Kabir Verma',
    createdAt: '2026-09-22T13:15:00.000Z',
    isPublic: true,
  },
  {
    id: 'item_returned_calc_05',
    reportCode: 'FB-2026-104',
    title: 'Scientific Calculator',
    description: 'Casio fx-991EX ClassWiz engineering calculator with solar strip and hard slide cover.',
    additionalDetails: 'Initials engraved on the inside cover.',
    category: 'Stationery',
    type: 'lost',
    date: '2026-09-14',
    location: 'Examination Hall',
    image: calculatorImg,
    status: 'Returned',
    userId: 'student_tanya_01',
    reporterName: 'Tanya Garg',
    createdAt: '2026-09-14T12:45:00.000Z',
    isPublic: true,
  },
  {
    id: 'item_found_bottle_06',
    reportCode: 'FB-2026-105',
    title: 'Silver Water Bottle',
    description: 'Brushed stainless steel insulated flask with a matte black loop cap.',
    additionalDetails: 'Available for pickup at the Seminar Hall Coordinator office.',
    category: 'Other',
    type: 'found',
    date: '2026-09-24',
    location: 'Seminar Hall',
    image: waterBottleImg,
    status: 'Reported',
    userId: 'faculty_rao_05',
    reporterName: 'Prof. S. Rao',
    createdAt: '2026-09-24T17:10:00.000Z',
    isPublic: true,
  },
];

export const INITIAL_DEMO_MATCHES: ItemMatch[] = [
  {
    id: 'match_earbuds_92',
    lostItemId: 'item_lost_earbuds_01',
    foundItemId: 'item_lost_earbuds_01',
    lostItemTitle: 'Black Boat Earbuds',
    foundItemTitle: 'Black Wireless Earbuds',
    matchScore: 92,
    categoryMatch: true,
    descriptionSimilarity: true,
    locationMatch: true,
    dateMatch: true,
    reasonsSummary: 'Same category · Similar description · Same location · Same date',
    status: 'Active',
    createdBy: 'system_matcher',
    createdAt: '2026-09-18T14:06:00.000Z',
    isPublic: true,
  },
];

export const INITIAL_DEMO_CLAIMS: OwnershipClaim[] = [
  {
    id: 'claim_demo_calc_01',
    itemId: 'item_returned_calc_05',
    itemTitle: 'Scientific Calculator',
    claimantId: 'student_tanya_01',
    claimantName: 'Tanya Garg',
    uniqueFeature: 'Initials "T.G." lightly engraved on the inside of the hard slide cover.',
    attachedContents: 'Formula reference sticker on the back casing.',
    exactLastSeen: 'Examination Hall Row C Seat 14.',
    status: 'Approved',
    adminNotes: 'Ownership verified and returned.',
    createdAt: '2026-09-15T10:00:00.000Z',
  },
];

export const INITIAL_DEMO_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_demo_01',
    userId: 'student_tanya_01',
    message: 'Possible match found — Your Black Earbuds may have been found.',
    type: 'match',
    relatedItemId: 'item_lost_earbuds_01',
    read: false,
    createdAt: '2026-09-18T14:06:00.000Z',
  },
  {
    id: 'notif_demo_02',
    userId: 'student_tanya_01',
    message: 'Claim verified — Your ownership verification was approved.',
    type: 'verified',
    relatedItemId: 'item_returned_calc_05',
    read: false,
    createdAt: '2026-09-16T11:20:00.000Z',
  },
  {
    id: 'notif_demo_03',
    userId: 'student_tanya_01',
    message: 'Item returned — Your Scientific Calculator has been marked as returned.',
    type: 'returned',
    relatedItemId: 'item_returned_calc_05',
    read: true,
    createdAt: '2026-09-15T15:30:00.000Z',
  },
];

export const INITIAL_DEMO_USERS: UserProfile[] = [
  {
    uid: 'student_tanya_01',
    name: 'Tanya Garg',
    email: 'taniyagarg1007@gmail.com',
    role: 'student',
    department: 'Computer Science & Engineering',
    createdAt: '2026-08-01T09:00:00.000Z',
  },
  {
    uid: 'student_kabir_03',
    name: 'Kabir Verma',
    email: 'kabir.verma@campus.edu',
    role: 'student',
    department: 'Mechanical Engineering',
    createdAt: '2026-08-06T09:00:00.000Z',
  },
  {
    uid: 'admin_campus_01',
    name: 'Campus Admin',
    email: 'admin@campus.edu',
    role: 'admin',
    department: 'Student Welfare & Security',
    createdAt: '2026-08-01T08:00:00.000Z',
  },
];
